---
title: "App Name Here"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: "https://github.com/cds490-top-fall20/air-quality"
    theme: cerulean
runtime: shiny
---

```{r global, include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(leaflet))
suppressPackageStartupMessages(library(sf))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(leafpop))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(flexdashboard))
suppressPackageStartupMessages(library(RColorBrewer))


full_data <- read_rds("data/counties_mapping_data_simplified.rds") %>% 
  mutate(
    `Pollutant Grade` = case_when(
      `Pollutant Grade` == "DNC" ~ NA_character_,
      `Pollutant Grade` == "INC" ~ NA_character_,
      TRUE ~ `Pollutant Grade`,
    ),
    `Ozone Grade` = case_when(
      `Ozone Grade` == "DNC" ~ NA_character_,
      `Ozone Grade` == "INC" ~ NA_character_,
      TRUE ~ `Ozone Grade`,
    ),
    `Annual Pass/Fail` = case_when(
      `Annual Pass/Fail` == "DNC" ~ NA_character_,
      `Annual Pass/Fail` == "INC" ~ NA_character_,
      TRUE ~ `Annual Pass/Fail`,
    ),
    `Particle Pollution Grade` = as.factor(`Pollutant Grade`),
    `Ozone Grade` = as.factor(`Ozone Grade`),
    # `Annual Pass/Fail` = as.factor(`Annual Pass/Fail`),
    `Annual Pass/Fail` = factor(`Annual Pass/Fail`, c("PASS","FAIL"))
  )
metros <- read_rds("data/urban_areas_simplified.rds")
state_coords <- read_csv("data/state_coords.csv")
```


Map
===========

Inputs {.sidebar}
-----------------------------------------------------------------------

Want to live somewhere with cleaner air?

This dashboard shows the air quality in US counties, alongside transportation emissions, compared to housing
statistics (e.g. house price and rent).


### Customize

```{r}
state_names <- sort(unique(full_data$state_name))
selectInput(
  "state", 
  "Choose 1 or more US states to show:", 
  state_names,
  selected = "Virginia",
  multiple = TRUE
  )
```

```{r}
map_data <- reactive({
  if(is.null(input$state)) {
    return(full_data)
  }
  full_data %>% 
     filter(
        state_name %in% input$state
      )
  })
```

```{r}
selectInput(
  "Grade", 
  "What grade would you like to View?", 
  choices=c("Particle Pollution Grade"="Particle Pollution Grade",
            "Ozone Grade"="Ozone Grade",      
            "Annual Pass/Fail"="Annual Pass/Fail"))

```

Air quality grades are sourced from the National Lung Association's [State of the Air Report](https://www.stateoftheair.org/) for 2019.

Note: many counties do not have air quality sensors, and lack a grade.


Row 1 {data-height=650}
-----------------------------------------------------------------------

### Map


```{r}
output$sotaMap <- renderLeaflet(
  {
    factpal <- colorFactor(c("forestgreen","gold","firebrick1"), levels = levels(full_data[[input$Grade]]), na.color = "grey", ordered = T)

    leaflet(map_data()) %>% 
      setView(-98.585522, 39.8333333, 4) %>%
      addProviderTiles("Esri.WorldGrayCanvas") %>%
      addMapPane("metro_areas", zIndex = 400) %>%
      addMapPane("pollution_counties", zIndex = 420) %>%
      addPolygons(
        data = metros,
        color = "black",
        fillColor = "light grey",
        group = "Metro Areas",
        options = pathOptions(pane = "metro_areas")
      ) %>%
      hideGroup("Metro Areas") %>%
      addPolygons(
        # data = shape,
        label = ~county_name,
        fillColor = ~ factpal(map_data()[[input$Grade]]),
        layerId = ~GEOID,
        opacity = 1,
        weight = 1,
        color = "white",
        dashArray = "3",
        fillOpacity = 0.5,
        popup = paste(
          "County:", full_data$county_name,"<br>",
          "Selected Grade:", full_data[[input$Grade]] ,"<br>"
          ),
        highlight = highlightOptions(
          weight = 5,
          color = "#666",
          dashArray = "",
          fillOpacity = 0.7,
          bringToFront = TRUE
          )
        ) %>% 
      addLegend(
        pal = factpal, 
        values = ~full_data[[input$Grade]], 
        opacity = 0.7, 
        title = NULL,
        position = "bottomright"
        ) %>%
      addLabelOnlyMarkers(
        lng = ~metros$long,
        lat = ~metros$lat,
        label = ~metros$name,
        labelOptions = labelOptions(noHide = T, direction = 'center', textOnly = T),
        group = "Metro Areas",
        options = pathOptions(pane = "metro_areas")
        ) %>%
      addLayersControl(
        overlayGroups = c("Metro Areas"),
        options = layersControlOptions(collapsed = FALSE)
      )
    }
  )
leafletOutput("sotaMap")
```


Row 2 {data-height=350}
-------



### County stats

```{r}
clicked_county <- reactive({
  # print(input$sotaMap_shape_click)
  if (is.null(input$sotaMap_shape_click$id) == FALSE){
    county_stats <- map_data() %>%
      filter(GEOID == input$sotaMap_shape_click$id)
    return(HTML(
      "<b>County information for:</b>", county_stats$county_name,
      "<br><b>Median house price: $</b>", county_stats$median_house_value,
      "<br><b>Median rent: $</b>", county_stats$median_rent,
      "<br><b>% of People who commute into this county:</b>", 
      round(100 * county_stats$commute_within / county_stats$num_residents),
      "<br><b>% of People who commute to other counties:</b>", 
      round(100 * county_stats$commute_out / county_stats$num_residents),
      "<br><b>% of People who commute within county:</b>", 
      round(100 * county_stats$commute_within / county_stats$num_residents)
      ))
  }
  return(HTML("<p>Click on a county to display more information</p>"))
})
renderUI(clicked_county())
```

    
### Why should you care?

* Pollution from transportation has a large effect on air quality (but other factors also affect air quality).

* Poor air quality can have a large impact on health.

* Pollution Grades
  * Particle Pollution: grade based on average PM2.5 concentration (breathable particles smaller than 2.5 micrometers)
  * Ozone: grade based on average ozone concentration
  * Annual Pass/Fail: counties with air quality levels better than the EPA's National Ambient Air Quality Standard receive a passing grade


Compare
========

Inputs {.sidebar}
-----------------------------------------------------------------------

Select 2 counties to compare air quality and housing statistics for those
counties.

### Pick two counties
```{r}
county_list <- full_data$GEOID

names(county_list) <- paste(full_data$county_name, full_data$state_name, sep = ", ")
county_list <- county_list[order(names(county_list))]
```

```{r}
selectInput("county1", "Choose first county to compare:", county_list)

county1_df <- reactive({
  filter(full_data, GEOID == input$county1)
})
```

```{r}
selectInput("county2", "Choose second county to compare:", county_list)

county2_df <- reactive({
  filter(full_data, GEOID == input$county2)
})
```

```{r}
particle_pal <- colorFactor(c("forestgreen","gold","firebrick1"), levels = levels(full_data$`Particle Pollution Grade`), na.color = "grey", ordered = T)
ozone_pal <- colorFactor(c("forestgreen","gold","firebrick1"), levels = levels(full_data$`Ozone Grade`), na.color = "grey", ordered = T)
passfail_pal <- colorFactor(c("forestgreen","gold","firebrick1"), levels = levels(full_data$`Annual Pass/Fail`), na.color = "grey", ordered = T)

max_house_price <- max(full_data$median_house_value, na.rm = TRUE)
max_rent <- max(full_data$median_rent, na.rm = TRUE)
```



Row 1, County 1
------------

### Particle Pollution Grade

```{r}
renderValueBox({
  value <- county1_df()$`Particle Pollution Grade`
  valueBox(value, " Particle Pollution Grade",
           icon = "ion-fireball",
           color = particle_pal(value))
})
```

### Ozone Grade

```{r}
renderValueBox({
  value <- county1_df()$`Ozone Grade`
  valueBox(value, " Ozone Grade",
           icon = "ion-fireball",
           color = ozone_pal(value))
})
```

### Annual Pass/Fail

```{r}
renderValueBox({
  value <- county1_df()$`Annual Pass/Fail`
  valueBox(value, " Annual Pass/Fail Grade",
           icon = "ion-fireball",
           color = passfail_pal(value))
})
```


### Average house price

```{r}
renderGauge({
  rate <- county1_df()$median_house_value
  gauge(
    rate, 
    min = 0, max = max_house_price, 
    symbol = '$', 
    gaugeSectors(
      success = c(0, max_house_price * 0.25), 
      warning = c(max_house_price * 0.25, max_house_price * 0.75), 
      danger = c(max_house_price * 0.75, max_house_price)
  ))
})
```

### Average rent

```{r}
renderGauge({
  rate <- county1_df()$median_rent
  gauge(
    rate, 
    min = 0, max = max_rent, 
    symbol = '$', 
    gaugeSectors(
      success = c(0, max_rent * 0.25), 
      warning = c(max_rent * 0.25, max_rent * 0.75), 
      danger = c(max_rent * 0.75, max_rent)
  ))
})
```


Row 2, County 2
------------

### Particle Pollution Grade

```{r}
renderValueBox({
  value <- county2_df()$`Particle Pollution Grade`
  valueBox(value, " Particle Pollution Grade",
           icon = "ion-fireball",
           color = particle_pal(value))
})
```

### Ozone Grade

```{r}
renderValueBox({
  value <- county2_df()$`Ozone Grade`
  valueBox(value, " Ozone Grade",
           icon = "ion-fireball",
           color = ozone_pal(value))
})
```

### Annual Pass/Fail

```{r}
renderValueBox({
  value <- county2_df()$`Annual Pass/Fail`
  valueBox(value, " Annual Pass/Fail Grade",
           icon = "ion-fireball",
           color = passfail_pal(value))
})
```


### Average house price

```{r}
renderGauge({
  rate <- county2_df()$median_house_value
  gauge(
    rate, 
    min = 0, max = max_house_price, 
    symbol = '$', 
    gaugeSectors(
      success = c(0, max_house_price * 0.25), 
      warning = c(max_house_price * 0.25, max_house_price * 0.75), 
      danger = c(max_house_price * 0.75, max_house_price)
  ))
})
```

### Average rent

```{r}
renderGauge({
  rate <- county2_df()$median_rent
  gauge(
    rate, 
    min = 0, max = max_rent, 
    symbol = '$', 
    gaugeSectors(
      success = c(0, max_rent * 0.25), 
      warning = c(max_rent * 0.25, max_rent * 0.75), 
      danger = c(max_rent * 0.75, max_rent)
  ))
})
```

Data
=====


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("datatable_state", "Choose a state:",
      sort(unique(full_data$state_name))
    )
```

## Row 1

### Data



```{r}
DT::renderDataTable({
  full_data %>%
    filter(state_name == input$datatable_state )%>%
    # select(
    #   County = county_name,
    #   State = state_name,
    #   `Avg. house price` = median_house_price,
    #   `Avg. rent` = median_rent,
    #   `Particle Pollution Grade`,
    #   `Ozone Grade`,
    #   `Annual Pass/Fail`
    #   ) %>%
    datatable()
})
```


About
======

